server.port: 8080

auth0:
  audience: ${auth0.audience}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.domain}
  datasource:
    url: ${jdbc:postgresql://PGHOST:PGPORT/PGDATABASE:jdbc:postgresql://localhost:5430/tdl-api}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml